theme: jekyll-theme-minimal
title: Nathan Nguyen
description: Computer Science Student @ Georgia Institute of Technology
image:
  path: "nnguyen402/professional_picture.jpg"
author: ""
show_downloads: true
