theme: jekyll-theme-minimal
title: Nathan Nguyen
description: Computer Science Student @ Georgia Institute of Technology
image:
  url: "https://github.com/nnguyen402/nnguyen402/blob/main/professional_picture.jpg"
author: ""
show_downloads: true
